"""create career roles and skill requirements

Revision ID: 33f22ec2b7ac
Revises: ae10781ef549
Create Date: 2026-09-08 09:18:21.416793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33f22ec2b7ac'
down_revision: Union[str, Sequence[str], None] = 'ae10781ef549'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('ayush_system_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ayush_system_id'], ['ayush_systems.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_roles_name'), 'career_roles', ['name'], unique=True)
    op.create_table('career_role_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('career_role_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('required_score', sa.Float(), nullable=False),
    sa.Column('importance_weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['career_role_id'], ['career_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('career_role_id', 'skill_id', name='uq_career_role_skill')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('career_role_skills')
    op.drop_index(op.f('ix_career_roles_name'), table_name='career_roles')
    op.drop_table('career_roles')
    # ### end Alembic commands ###
