"""create AYUSH skill foundation

Revision ID: 58f9101e8977
Revises: 13768d07a2da
Create Date: 2026-09-07 20:29:37.206568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58f9101e8977'
down_revision: Union[str, Sequence[str], None] = '13768d07a2da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ayush_systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.add_column('skill_categories', sa.Column('ayush_system_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('skill_categories_name_key'), 'skill_categories', type_='unique')
    op.create_unique_constraint('uq_ayush_skill_category', 'skill_categories', ['ayush_system_id', 'name'])
    op.create_foreign_key(None, 'skill_categories', 'ayush_systems', ['ayush_system_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=False)
    op.create_unique_constraint('uq_category_skill', 'skills', ['category_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_category_skill', 'skills', type_='unique')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    op.drop_constraint(None, 'skill_categories', type_='foreignkey')
    op.drop_constraint('uq_ayush_skill_category', 'skill_categories', type_='unique')
    op.create_unique_constraint(op.f('skill_categories_name_key'), 'skill_categories', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('skill_categories', 'ayush_system_id')
    op.drop_table('ayush_systems')
    # ### end Alembic commands ###
