"""add internship and job opportunities

Revision ID: 59f5f8baf3a3
Revises: 61c9c9304d3d
Create Date: 2026-09-08 11:33:02.668298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59f5f8baf3a3'
down_revision: Union[str, Sequence[str], None] = '61c9c9304d3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('industry_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('eligibility', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=250), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('stipend', sa.Float(), nullable=True),
    sa.Column('application_deadline', sa.DateTime(), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('official_url', sa.String(length=1000), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('industry_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('eligibility', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=250), nullable=True),
    sa.Column('employment_type', sa.String(length=100), nullable=True),
    sa.Column('salary_min', sa.Float(), nullable=True),
    sa.Column('salary_max', sa.Float(), nullable=True),
    sa.Column('application_deadline', sa.DateTime(), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('official_url', sa.String(length=1000), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunity_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internship_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('required_score', sa.Float(), nullable=False),
    sa.Column('importance_weight', sa.Float(), nullable=False),
       sa.ForeignKeyConstraint(['internship_id'], ['internships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('internship_id', 'skill_id', name='uq_internship_skill'),
    sa.UniqueConstraint('job_id', 'skill_id', name='uq_job_skill'),
    sa.CheckConstraint(
        "(internship_id IS NOT NULL AND job_id IS NULL) OR "
        "(internship_id IS NULL AND job_id IS NOT NULL)",
        name="ck_opportunity_skill_one_parent"
    )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opportunity_skills')
    op.drop_table('jobs')
    op.drop_table('internships')
    # ### end Alembic commands ###
