"""create internship completion

Revision ID: 7ea7058d993c
Revises: 95b85714726a
Create Date: 2026-09-09 00:05:20.120857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ea7058d993c'
down_revision: Union[str, Sequence[str], None] = '95b85714726a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internship_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internship_progress_id', sa.Integer(), nullable=False),
    sa.Column('final_progress_percentage', sa.Float(), nullable=False),
    sa.Column('final_attendance_percentage', sa.Float(), nullable=False),
    sa.Column('tasks_completed', sa.Integer(), nullable=False),
    sa.Column('total_tasks', sa.Integer(), nullable=False),
    sa.Column('mentor_rating', sa.Float(), nullable=False),
    sa.Column('mentor_evaluation', sa.Text(), nullable=True),
    sa.Column('student_report', sa.Text(), nullable=True),
    sa.Column('skills_demonstrated', sa.Text(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('areas_for_improvement', sa.Text(), nullable=True),
    sa.Column('completion_date', sa.DateTime(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verification_date', sa.DateTime(), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('certificate_url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['internship_progress_id'], ['internship_progress.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internship_completions_id'), 'internship_completions', ['id'], unique=False)
    op.create_index(op.f('ix_internship_completions_internship_progress_id'), 'internship_completions', ['internship_progress_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_internship_completions_internship_progress_id'), table_name='internship_completions')
    op.drop_index(op.f('ix_internship_completions_id'), table_name='internship_completions')
    op.drop_table('internship_completions')
    # ### end Alembic commands ###
