"""create internship progress

Revision ID: 95b85714726a
Revises: a3eb90ac253b
Create Date: 2026-09-08 22:10:19.210665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95b85714726a'
down_revision: Union[str, Sequence[str], None] = 'a3eb90ac253b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internship_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('progress_percentage', sa.Float(), nullable=False),
    sa.Column('tasks_completed', sa.Integer(), nullable=False),
    sa.Column('total_tasks', sa.Integer(), nullable=False),
    sa.Column('attendance_percentage', sa.Float(), nullable=False),
    sa.Column('student_notes', sa.Text(), nullable=True),
    sa.Column('mentor_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mentor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internship_progress_application_id'), 'internship_progress', ['application_id'], unique=True)
    op.create_index(op.f('ix_internship_progress_id'), 'internship_progress', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_internship_progress_id'), table_name='internship_progress')
    op.drop_index(op.f('ix_internship_progress_application_id'), table_name='internship_progress')
    op.drop_table('internship_progress')
    # ### end Alembic commands ###
