"""add shortlists

Revision ID: a3eb90ac253b
Revises: e2abcb080e11
Create Date: 2026-09-08 16:36:57.233273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3eb90ac253b'
down_revision: Union[str, Sequence[str], None] = 'e2abcb080e11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shortlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('recruitment_score', sa.Float(), nullable=False),
    sa.Column('skill_match_percentage', sa.Float(), nullable=False),
    sa.Column('assessment_coverage_percentage', sa.Float(), nullable=False),
    sa.Column('eligibility_status', sa.Boolean(), nullable=False),
    sa.Column('shortlist_type', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('shortlisted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shortlisted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', name='uq_shortlist_application')
    )
    op.create_index(op.f('ix_shortlists_application_id'), 'shortlists', ['application_id'], unique=True)
    op.create_index(op.f('ix_shortlists_id'), 'shortlists', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shortlists_id'), table_name='shortlists')
    op.drop_index(op.f('ix_shortlists_application_id'), table_name='shortlists')
    op.drop_table('shortlists')
    # ### end Alembic commands ###
