"""create courses and course skills

Revision ID: d99f345b6ff2
Revises: 8e16d23b5a3e
Create Date: 2026-09-09 08:28:05.339587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd99f345b6ff2'
down_revision: Union[str, Sequence[str], None] = '8e16d23b5a3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=300), nullable=True),
    sa.Column('course_type', sa.String(length=50), nullable=False),
    sa.Column('difficulty_level', sa.String(length=50), nullable=False),
    sa.Column('duration_hours', sa.Float(), nullable=True),
    sa.Column('certification_available', sa.Boolean(), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('official_url', sa.String(length=1000), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_table('course_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('target_level', sa.Integer(), nullable=True),
    sa.Column('coverage_percentage', sa.Float(), nullable=False),
    sa.Column('importance_weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'skill_id', name='uq_course_skill')
    )
    op.create_index(op.f('ix_course_skills_course_id'), 'course_skills', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_skills_id'), 'course_skills', ['id'], unique=False)
    op.create_index(op.f('ix_course_skills_skill_id'), 'course_skills', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_skills_skill_id'), table_name='course_skills')
    op.drop_index(op.f('ix_course_skills_id'), table_name='course_skills')
    op.drop_index(op.f('ix_course_skills_course_id'), table_name='course_skills')
    op.drop_table('course_skills')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
