"""add skill verification fields

Revision ID: dc7f03b25862
Revises: 6ae90a050fe8
Create Date: 2026-09-09 07:01:03.662583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc7f03b25862'
down_revision: Union[str, Sequence[str], None] = '6ae90a050fe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_skills', sa.Column('verified_by', sa.Integer(), nullable=True))
    op.add_column('student_skills', sa.Column('verified_at', sa.DateTime(), nullable=True))
    op.add_column('student_skills', sa.Column('verification_source', sa.String(length=50), nullable=True))
    op.add_column('student_skills', sa.Column('verification_notes', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'student_skills', 'users', ['verified_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_skills', type_='foreignkey')
    op.drop_column('student_skills', 'verification_notes')
    op.drop_column('student_skills', 'verification_source')
    op.drop_column('student_skills', 'verified_at')
    op.drop_column('student_skills', 'verified_by')
    # ### end Alembic commands ###
