"""add skill demand analytics

Revision ID: ed46f1890194
Revises: fcd22a341375
Create Date: 2026-09-09 09:30:24.471056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed46f1890194'
down_revision: Union[str, Sequence[str], None] = 'fcd22a341375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_demand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('demand_count', sa.Integer(), nullable=False),
    sa.Column('student_supply_count', sa.Integer(), nullable=False),
    sa.Column('skill_gap_count', sa.Integer(), nullable=False),
    sa.Column('demand_score', sa.Float(), nullable=False),
    sa.Column('growth_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_id', 'period', name='uq_skill_demand_period')
    )
    op.create_index(op.f('ix_skill_demand_id'), 'skill_demand', ['id'], unique=False)
    op.create_index(op.f('ix_skill_demand_period'), 'skill_demand', ['period'], unique=False)
    op.create_index(op.f('ix_skill_demand_skill_id'), 'skill_demand', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_demand_skill_id'), table_name='skill_demand')
    op.drop_index(op.f('ix_skill_demand_period'), table_name='skill_demand')
    op.drop_index(op.f('ix_skill_demand_id'), table_name='skill_demand')
    op.drop_table('skill_demand')
    # ### end Alembic commands ###
