"""add career paths

Revision ID: fcd22a341375
Revises: d99f345b6ff2
Create Date: 2026-09-09 09:04:23.807445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcd22a341375'
down_revision: Union[str, Sequence[str], None] = 'd99f345b6ff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_paths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('career_role_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['career_role_id'], ['career_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_paths_career_role_id'), 'career_paths', ['career_role_id'], unique=False)
    op.create_index(op.f('ix_career_paths_id'), 'career_paths', ['id'], unique=False)
    op.create_table('career_path_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('career_path_id', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('step_type', sa.String(length=50), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('target_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['career_path_id'], ['career_paths.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('career_path_id', 'step_order', name='uq_career_path_step_order')
    )
    op.create_index(op.f('ix_career_path_steps_career_path_id'), 'career_path_steps', ['career_path_id'], unique=False)
    op.create_index(op.f('ix_career_path_steps_id'), 'career_path_steps', ['id'], unique=False)
    op.create_index(op.f('ix_career_role_skills_career_role_id'), 'career_role_skills', ['career_role_id'], unique=False)
    op.create_index(op.f('ix_career_role_skills_id'), 'career_role_skills', ['id'], unique=False)
    op.create_index(op.f('ix_career_role_skills_skill_id'), 'career_role_skills', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_career_role_skills_skill_id'), table_name='career_role_skills')
    op.drop_index(op.f('ix_career_role_skills_id'), table_name='career_role_skills')
    op.drop_index(op.f('ix_career_role_skills_career_role_id'), table_name='career_role_skills')
    op.drop_index(op.f('ix_career_path_steps_id'), table_name='career_path_steps')
    op.drop_index(op.f('ix_career_path_steps_career_path_id'), table_name='career_path_steps')
    op.drop_table('career_path_steps')
    op.drop_index(op.f('ix_career_paths_id'), table_name='career_paths')
    op.drop_index(op.f('ix_career_paths_career_role_id'), table_name='career_paths')
    op.drop_table('career_paths')
    # ### end Alembic commands ###
